### ISSUE TITLE
大哥辛苦了，原来不是只有我一个人搞 ons 引擎

### ISSUE THREAD

**Issue by zeromake** [pch666777/onscripter-LONSdev#1]
我整了个 [ONScripter-zero](https://github.com/zeromake/ONScripter-zero)，我最近也在想事件和渲染的分离，但是没有想好（代码修改量巨大）。

有几个问题想问一下：

- 项目有开源协议吗（完全重写的应该是想用什么协议就用啥吧）？
- 项目的安卓项目工程是没有在这个仓库里？

**Comment by pch666777** [comment]
1、已添加MIT协议，说明里会增加关于代码用途的说明。
2、我嫌各种工程文件又多又杂，没有加入安卓代码到此工程中。单纯的就是拿SDL2的安卓工程改了一下。
事件和渲染分离是我一开始的想法，不过这个想法如果依赖SDL2的话是无法实现的，因为渲染本身就被限制在主线程（子线程在某些平台上会卡死），事件的获取也被限制在主线程（SDL的说明里确实是这么要求的）。目前我只是把脚本和渲染分开，不过这也带来大量的线程同步问题，有好有坏。
最后本人水平问题，代码确实写得跟一坨屎一样，有问题可以邮pngchs@qq.com，某些原因，上github总是不顺畅。

**Comment by zeromake** [comment]
@pch666777 
和我想法差不多，不过想的是 worker 模式，构建几个 io，计算线程池，把耗时任务提交进去，并且把渲染更新回调也提交进去，然后把调度写好就完事了（安卓就是这套方案，不过不用 rx 也是难受的要死）

**Comment by zeromake** [comment]
顺便一提脚本解析没有使用 tree-sitter 之类的语法解析器去做啊（之前也尝试过其它的太难了，只有 tree-sitter 学会了），我已经被原版 ons 的解析快搞崩溃了，之前不懂 ons 正文是不支持英文半角，直接把正文的英文半角支持了，然后各种解析错误，调试 n 久才整好，现在想来有一个 ast 语法树就好调太多了。

**Comment by pch666777** [comment]
我并没有使用任何语法分析工具，也没有语法分析结果，感觉ons更倾向于过程式的。命令我通过命令参数模版匹配每一个参数允许的类型，是否缺省等，可以识别出大部分命令参数错误，即使是这样也有少量奇葩命令不能通过模版匹配。运算使用逆波兰式算法，?[]%$完美的包含进入，从现在的结果上看还是非常成功的，比原ONS在运算的表达能力上要强。通过这两个基本能解决问题了。
线程池原先也考虑过，又感觉杀鸡用牛刀，毕竟现在的ons游戏都是为单线程设计的，以后还有不有新的ons游戏，可能还不一定，现在用ons的确实不多了。虽然我也想移植一两个表现力强的游戏，未来的事谁知道呢，摊手。
